services:
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5

  memcached:
    image: memcached:alpine
    ports:
      - '11211:11211'
    healthcheck:
      test: ['CMD', 'nc', '-z', 'localhost', '11211']
      interval: 5s
      timeout: 5s
      retries: 5
